### ISSUE TITLE
use a jobcontext to get the jobid

### ISSUE THREAD

**Issue by vip32** [samshiles/hangfire.job.logging#1]
first thanks for sharing the idea to insert in the state table directly.
however, you don't need to inject the jobid, using a jobcontext makes it much easier and transparant
this can be used inside your joblogger to get the right jobid. i just did that in my project and works really well.

```
public class JobContext : IServerFilter
{
    [ThreadStatic]
    private static string _jobId;
    [ThreadStatic]
    private static Type _jobType;

    public static string JobId { get { return _jobId; } set { _jobId = value; } }

    public static Type JobType { get { return _jobType; } set { _jobType = value; } }

    public void OnPerforming(PerformingContext context)
    {
        JobId = context.JobId;
        JobType = context.Job.Type;
    }

    public void OnPerformed(PerformedContext filterContext)
    {
    }
   }
```

and configure this filter:
GlobalConfiguration.Configuration.UseFilter(new JobContext())

**Comment by Recodify** [comment]
Hi, thanks for this. How would I then get a reference to this JobContext in my logger?

**Comment by vip32** [comment]
the JobId is a static. you can just call JobContext.JobId and it works.
